export const quizData = {
  questionsList: [
    {
      id: 1,
      questionTitle: "What is the capital of France?",
      choices: ["Berlin", "Madrid", "Paris", "Lisbon"],
      answerIndex: [2],
    },
    {
      id: 2,
      questionTitle: "Which of the following are programming languages?",
      choices: ["Python", "HTML", "CSS", "JavaScript"],
      answerIndex: [0, 3],
    },
    {
      id: 3,
      questionTitle: "What is the largest planet in our Solar System?",
      choices: ["Earth", "Mars", "Jupiter", "Saturn"],
      answerIndex: [2],
    },
    {
      id: 4,
      questionTitle: "Which elements are noble gases?",
      choices: ["Hydrogen", "Neon", "Argon", "Oxygen"],
      answerIndex: [1, 2],
    },
    {
      id: 5,
      questionTitle: "What is the boiling point of water in Celsius?",
      choices: ["50", "75", "100", "150"],
      answerIndex: [2],
    },
    {
      id: 6,
      questionTitle: "Which of the following are continents?",
      choices: ["Australia", "Greenland", "Antarctica", "New Zealand"],
      answerIndex: [0, 2],
    },
    {
      id: 7,
      questionTitle: "Who wrote 'To Kill a Mockingbird'?",
      choices: ["Harper Lee", "J.K. Rowling", "Ernest Hemingway", "Mark Twain"],
      answerIndex: [0],
    },
    {
      id: 8,
      questionTitle: "Which of these are prime numbers?",
      choices: ["4", "7", "9", "11"],
      answerIndex: [1, 3],
    },
    {
      id: 9,
      questionTitle: "What is the chemical symbol for gold?",
      choices: ["Au", "Ag", "Pb", "Fe"],
      answerIndex: [0],
    },
    {
      id: 10,
      questionTitle: "Which of these are classical music composers?",
      choices: ["Beethoven", "Mozart", "Bach", "Chopin"],
      answerIndex: [0, 1, 2, 3],
    },
    {
      id: 11,
      questionTitle: "What is the main language spoken in Brazil?",
      choices: ["Spanish", "Portuguese", "English", "French"],
      answerIndex: [1],
    },
    {
      id: 12,
      questionTitle: "Which of these are renewable energy sources?",
      choices: ["Solar", "Coal", "Wind", "Natural Gas"],
      answerIndex: [0, 2],
    },
    {
      id: 13,
      questionTitle: "What are the primary colors?",
      choices: ["Red", "Green", "Blue", "Yellow"],
      answerIndex: [0, 2],
    },
    {
      id: 14,
      questionTitle: "Which planets are known as gas giants?",
      choices: ["Earth", "Jupiter", "Uranus", "Venus"],
      answerIndex: [1, 2],
    },
    {
      id: 15,
      questionTitle: "Who painted the Mona Lisa?",
      choices: [
        "Vincent van Gogh",
        "Claude Monet",
        "Leonardo da Vinci",
        "Pablo Picasso",
      ],
      answerIndex: [2],
    },
    {
      id: 16,
      questionTitle: "What is the hardest natural substance on Earth?",
      choices: ["Gold", "Diamond", "Iron", "Platinum"],
      answerIndex: [1],
    },
    {
      id: 17,
      questionTitle: "Which of the following are Shakespearean plays?",
      choices: ["Hamlet", "Macbeth", "The Tempest", "Don Quixote"],
      answerIndex: [0, 1, 2],
    },
    {
      id: 18,
      questionTitle: "Which countries are part of the United Kingdom?",
      choices: ["England", "Scotland", "Wales", "Ireland"],
      answerIndex: [0, 1, 2],
    },
    {
      id: 19,
      questionTitle: "What is the chemical formula for water?",
      choices: ["H2O", "CO2", "NaCl", "O2"],
      answerIndex: [0],
    },
    {
      id: 20,
      questionTitle: "Which of these are natural satellites of Earth?",
      choices: ["Moon", "Phobos", "Deimos", "Europa"],
      answerIndex: [0],
    },
    {
      id: 21,
      questionTitle: "What is the main ingredient in guacamole?",
      choices: ["Tomato", "Onion", "Avocado", "Pepper"],
      answerIndex: [2],
    },
    {
      id: 22,
      questionTitle: "Which of these are known for their high protein content?",
      choices: ["Chicken", "Broccoli", "Almonds", "Rice"],
      answerIndex: [0, 2],
    },
    {
      id: 23,
      questionTitle: "What are the basic types of rock?",
      choices: ["Igneous", "Sedimentary", "Metamorphic", "Granite"],
      answerIndex: [0, 1, 2],
    },
    {
      id: 24,
      questionTitle: "Which languages are written from left to right?",
      choices: ["English", "Arabic", "Chinese", "Spanish"],
      answerIndex: [0, 3],
    },
    {
      id: 25,
      questionTitle: "What are the components of an atom?",
      choices: ["Protons", "Neutrons", "Electrons", "Neurons"],
      answerIndex: [0, 1, 2],
    },
    {
      id: 26,
      questionTitle: "Which of these are considered programming paradigms?",
      choices: ["Object-Oriented", "Functional", "Procedural", "Structural"],
      answerIndex: [0, 1, 2, 3],
    },
    {
      id: 27,
      questionTitle: "Which animals are mammals?",
      choices: ["Elephant", "Shark", "Eagle", "Human"],
      answerIndex: [0, 3],
    },
    {
      id: 28,
      questionTitle: "What are the basic elements of a story?",
      choices: ["Characters", "Setting", "Plot", "Resolution"],
      answerIndex: [0, 1, 2, 3],
    },
    {
      id: 29,
      questionTitle: "Which of these countries are in Africa?",
      choices: ["Egypt", "Brazil", "Australia", "South Africa"],
      answerIndex: [0, 3],
    },
    {
      id: 30,
      questionTitle: "Who is known as the father of modern physics?",
      choices: [
        "Isaac Newton",
        "Albert Einstein",
        "Galileo Galilei",
        "Niels Bohr",
      ],
      answerIndex: [1],
    },
    {
      id: 31,
      questionTitle: "Which of these are types of clouds?",
      choices: ["Cumulus", "Stratus", "Cirrus", "Nimbostratus"],
      answerIndex: [0, 1, 2, 3],
    },
    {
      id: 32,
      questionTitle: "What is the currency of Japan?",
      choices: ["Yuan", "Won", "Yen", "Ringgit"],
      answerIndex: [2],
    },
    {
      id: 33,
      questionTitle: "Which elements are metals?",
      choices: ["Iron", "Sulfur", "Copper", "Neon"],
      answerIndex: [0, 2],
    },
    {
      id: 34,
      questionTitle: "Which of these are parts of the human digestive system?",
      choices: ["Stomach", "Liver", "Lungs", "Pancreas"],
      answerIndex: [0, 1, 3],
    },
    {
      id: 35,
      questionTitle: "What are the main types of musical instruments?",
      choices: ["String", "Percussion", "Wind", "Electronic"],
      answerIndex: [0, 1, 2, 3],
    },
    {
      id: 36,
      questionTitle: "What are the key principles of democracy?",
      choices: ["Freedom", "Equality", "Justice", "Dictatorship"],
      answerIndex: [0, 1, 2],
    },
    {
      id: 37,
      questionTitle: "Which of these are types of energy?",
      choices: ["Kinetic", "Thermal", "Potential", "Mechanical"],
      answerIndex: [0, 1, 2, 3],
    },
    {
      id: 38,
      questionTitle:
        "What are the primary functions of the respiratory system?",
      choices: ["Breathing", "Circulation", "Gas Exchange", "Digestion"],
      answerIndex: [0, 2],
    },
    {
      id: 39,
      questionTitle: "Which of these are considered basic human emotions?",
      choices: ["Happiness", "Sadness", "Anger", "Jealousy"],
      answerIndex: [0, 1, 2],
    },
    {
      id: 40,
      questionTitle: "What are the major components of a computer system?",
      choices: ["CPU", "RAM", "Hard Drive", "Monitor"],
      answerIndex: [0, 1, 2],
    },
    {
      id: 41,
      questionTitle: "Which of these are types of literature genres?",
      choices: ["Novel", "Poetry", "Drama", "Memoir"],
      answerIndex: [0, 1, 2, 3],
    },
    {
      id: 42,
      questionTitle: "Which continents are in the Northern Hemisphere?",
      choices: ["Africa", "Asia", "Europe", "Australia"],
      answerIndex: [1, 2],
    },
    {
      id: 43,
      questionTitle: "What are the four fundamental forces of nature?",
      choices: [
        "Gravity",
        "Electromagnetism",
        "Weak Nuclear",
        "Strong Nuclear",
      ],
      answerIndex: [0, 1, 2, 3],
    },
    {
      id: 44,
      questionTitle: "Which of these are oceanic bodies of water?",
      choices: [
        "Pacific Ocean",
        "Atlantic Ocean",
        "Mediterranean Sea",
        "Red Sea",
      ],
      answerIndex: [0, 1],
    },
    {
      id: 45,
      questionTitle: "What are common features of mammals?",
      choices: ["Hair", "Warm-blooded", "Lays Eggs", "Live Birth"],
      answerIndex: [0, 1, 3],
    },
    {
      id: 46,
      questionTitle: "Which of these are considered large-scale sports events?",
      choices: ["Olympics", "World Cup", "Tour de France", "NBA Finals"],
      answerIndex: [0, 1, 2],
    },
    {
      id: 47,
      questionTitle: "What are the components of the Earth’s atmosphere?",
      choices: ["Nitrogen", "Oxygen", "Carbon Dioxide", "Hydrogen"],
      answerIndex: [0, 1, 2],
    },
    {
      id: 48,
      questionTitle: "Which of these are famous landmarks in Paris?",
      choices: [
        "Eiffel Tower",
        "Louvre Museum",
        "Notre-Dame Cathedral",
        "Big Ben",
      ],
      answerIndex: [0, 1, 2],
    },
    {
      id: 49,
      questionTitle: "What are the stages of cellular respiration?",
      choices: [
        "Glycolysis",
        "Krebs Cycle",
        "Electron Transport Chain",
        "Photosynthesis",
      ],
      answerIndex: [0, 1, 2],
    },
    {
      id: 50,
      questionTitle: "Which of these are elements in the periodic table?",
      choices: ["Carbon", "Water", "Sodium", "Oxygen"],
      answerIndex: [0, 2, 3],
    },
  ],
};
